
development:
  adapter: postgresql
  encoding: unicode
  database: dimstore_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: dimstore_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: dimstore_production
  pool: 5
  username: postgres
  password: postgres
