
development:
  adapter: postgresql
  encoding: unicode
  database: dimstore_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: dimstore_test
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: dimstore_production
  pool: 5
  username: postgres
  password: 
